name: Itay
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  itay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: echo "Running tests..."
