name: Legit Workflow
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build_lint_test:
    uses: xxx/common-workflows/.x/workflows/xxx.yaml@xxx
    with:
      SHOULD_PUSH_SHARED_PACKAGE: false
      SHOULD_CREATE_MIGRATION_SCRIPT: true
      DB_NAME: AdoIntegrationService
      DOTNET_VERSION: "8.0"
      RESHARPER_VERSION: "2024.1.2"
    secrets: inherit
  generate_api_packages:
    uses: xxx/common-workflows/.x/workflows/xxx.yaml@xxx
    secrets: inherit
